### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by daifrrr** [mturk/cmsc#2]
Some "have to install" programms are out of date.

I did not "try hard" to make the necessary steps. I will try again.

Thank you 👍

**Comment by daifrrr** [comment]
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/1de7c9b4-1feb-4c98-b426-f7f02cbafa99/windows-sdk-71-on-windows-10?forum=windowssdk

to install Windows SDK 7

**Comment by mturk** [comment]
Sure that some of the dependencies are out of date.
On new DDK version Microsoft uses msvcrt-XXX.dll, thus there is no more dedicated compiler for device drivers.
